# Generated by Django 6.0.7 on 2026-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Внешний id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(db_index=True, max_length=128, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('updated_at', models.DateTimeField(verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-updated_at'],
            },
        ),
    ]
